### ISSUE TITLE
[BUG] hpss archive interface cant deal with latency config properly

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-archiveinterface#102]
### Pacifica Archive Interface version
0.3.0

### Platform Details
Centos 7

### Scenario:
use archive interface with hpss

### Steps to Reproduce:
try starting it, then read a file using the API

### Expected Result:
the file

### Actual Result:
```
Traceback (most recent call last):
  File "/opt/myemsl/lib/python3.6/site-packages/pacifica/archiveinterface/backends/hpss/archive.py", line 99, in open
    hpss.ping_core(self._sitename)
  File "/opt/myemsl/lib/python3.6/site-packages/pacifica/archiveinterface/backends/hpss/extended.py", line 39, in ping_core
    if latency > acceptable_latency:
TypeError: '>' not supported between instances of 'float' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/myemsl/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/opt/myemsl/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/opt/myemsl/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/myemsl/lib/python3.6/site-packages/cherrypy/lib/jsontools.py", line 59, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/myemsl/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/myemsl/lib/python3.6/site-packages/pacifica/archiveinterface/rest_generator.py", line 111, in POST
    archivefile = self._archive.open(filepath, 'r')
  File "/opt/myemsl/lib/python3.6/site-packages/pacifica/archiveinterface/backends/hpss/archive.py", line 123, in open
    raise ArchiveInterfaceError(err_str)
pacifica.archiveinterface.exception.ArchiveInterfaceError: Can't open hpss file with error: '>' not supported between instances of 'float' and 'str'
```

**Comment by karcaw** [comment]
Probably just need a getint at 
https://github.com/pacifica/pacifica-archiveinterface/blob/master/pacifica/archiveinterface/backends/hpss/extended.py#L27

**Comment by karcaw** [comment]
@dmlb2000 any chance you can fix this one this week?
