### ISSUE TITLE
Need for more specificity with PATCH documentation

### ISSUE THREAD

**Issue by stefangary** [pacifica/pacifica-archiveinterface#78]
### Pacifica Archive Interface version
archiveinterface:v0.2.0 container run via docker-compose

### Pacifica Core Software versions
pacifica/ingest-frontend:v0.3.3
pacifica/ingest-backend:v0.3.3
pacifica/notifications-backend:v0.3.2
pacifica/policy:v0.5.0
pacifica/proxy:v0.1.2
pacifica/metadata:v0.8.0
pacifica/cartd-frontend:v0.3.7
pacifica/cartd-backend:v0.3.7
pacifica/notifications-frontend:v0.3.2
pacifica/uniqueid:v0.3.3
docker.elastic.co/elasticsearch/elasticsearch:6.7.1
postgres:9.6
jupyter/scipy-notebook
rabbitmq:3.7

### Platform Details
Ubuntu 18.04
Docker version 18.09.5, build e8ff056, 
docker-compose version 1.24.0, build 0aa59064

### Scenario:
Cannot recreate example for PATCH operation in documentation at https://pacifica-archiveinterface.readthedocs.io/en/latest/exampleusage.html

### Steps to Reproduce:
docker-compose up followed by GET, PUT, HEAD examples in the same documentation.

### Expected Result:
Confirmation that the PATCH operation was completed, as in the docs.

### Actual Result:
> curl -X PATCH --upload-file original_path.json http://localhost:8080/67890
        {"status": "415 Unsupported Media Type", "message": "Expected an entity of content type application/json, text/javascript", "traceback": "Traceback (most recent call last):\n File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 630, in respond\n self._do_respond(path_info)\n File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 682, in _do_respond\n self.body.process()\n File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py", line 983, in process\n super(RequestBody, self).process()\n File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py", line 558, in process\n self.default_proc()\n File "/usr/local/lib/python2.7/site-packages/cherrypy/_cperror.py", line 416, in call\n raise self\nHTTPError: (415, u'Expected an entity of content type application/json, text/javascript')\n", "version": "17.4.1"}

I used this .json file to specify the original location of the file since that was the path specified by the output of the HEAD command in the documentation:
> {
> "path": "/srv/12345"
> }

The documentation provides this file as an example but it didn't work for me either:
> {
>  "path": "/path/to/file/file.1"
>}

Thanks!

**Comment by stefangary** [comment]
Dear David,
Thank you very much for addressing #77 and #78 in the documentation.  It is much clearer.  I found one small inconsistency between the docs and using Pacifica: when using the docker containers the files in these examples go to /srv/ by default and not to /tmp/ as is shown in the docs.  This difference in path is reflected in the output from the HEAD command and is needed to make the PATCH command successful.  Best, Stefan
